[package]
name = "dorimubot-framework-core"
version = "0.0.8"
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "基于 qqbot-rust-sdk 开发的QQ机器人开发框架"

[dependencies]
qqbot-rust-sdk = { workspace = true, features = ["events", "openapi", "signature"] }
serde.workspace = true
tokio.workspace = true
tracing.workspace = true

[dev-dependencies]
serde_json.workspace = true
trybuild = "1"
