[workspace]
members = [
    "dorimubot-framework",
    "dorimubot-framework/tests/facade-only",
    "dorimubot-framework-core",
    "dorimubot-axum",
    "dorimubot-commands",
    "dorimubot-commands-macros",
]
resolver = "2"

[workspace.package]
repository = "https://github.com/Dorimu-Nya/dorimubot-framework/"
license = "MIT OR Apache-2.0"
edition = "2021"

[workspace.dependencies]
base64 = "0.22"
dorimubot-axum = { version = "0.0.8", path = "dorimubot-axum" }
dorimubot-commands = { version = "0.0.8", path = "dorimubot-commands" }
dorimubot-commands-macros = { version = "0.0.5", path = "dorimubot-commands-macros" }
dorimubot-framework-core = { version = "0.0.8", path = "dorimubot-framework-core" }
inventory = "0.3.24"
qqbot-rust-sdk = { version = "0.0.10" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", features = ["rt-multi-thread", "macros", "sync", "time", "signal", "rt"] }
tracing = "0.1"
tracing-subscriber = "0.3"
