[package]
name = "dorimubot-framework"
version = "0.0.8"
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "基于 qqbot-rust-sdk 开发的QQ机器人开发框架"
exclude = ["tests/facade-only/**"]

[features]
default = ["axum-webhook", "commands", "commands-macros"]
axum-webhook = ["dep:dorimubot-axum"]
commands = ["dep:dorimubot-commands"]
commands-macros = ["dep:dorimubot-commands-macros"]

[dependencies]
dorimubot-framework-core.workspace = true
dorimubot-axum = { workspace = true, optional = true }
dorimubot-commands = { workspace = true, optional = true }
dorimubot-commands-macros = { workspace = true, optional = true }

[dev-dependencies]
qqbot-rust-sdk = { workspace = true, features = ["openapi"] }
tokio.workspace = true
